### ISSUE TITLE
이용에 대한 문의

### ISSUE THREAD

**Issue by jj9810** [DDosil/MapleSim#1]
안녕하세요, 얼마 전에 인터넷에서 메이플 스타포스 시뮬레이터를 알게 된 사람입니다.

이 프로젝트에 흥미를 가지게 되어 포크를 했고 일부 수정을 했습니다. 하지만 라이센스가 없는 프로젝트의 경우 임의로 수정하면 안된다는 사실을 뒤늦게 알게되어 문의를 드립니다. (해당 변경분은 제거된 상태입니다.) 사전에 연락을 드리지 않은 것에 대해 사과의 말씀을 드립니다.

혹시 이 프로젝트의 소스코드를 이용해도 될까요? 만약 허락해주시면 정해주시는 라이센스를 준수하도록 하겠습니다. 만약 안된다면 완전히 삭제하도록 하겠습니다.

**Comment by DDosil** [comment]
상업적인 용도만 아니라면 괜찮습니다. DPM 자료 잘 보고 있습니다.

**Comment by jj9810** [comment]
감사합니다.. 사실 dpm에서 제 기여분은 얼마 안돼요
